name: Happy

on:
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: actions/setup-node@v2
        with: 
            node-version: '12' #arreglo
      
      - name: Install RuboCop
        run: gem install rubocop
      
      - name: Run RuboCop
        run: rubocop
      
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: actions/setup-node@v2
        with: 
            node-version: '12'
    
      - name: Install dependencies
        run: bundle install
      
      - name: Run tests
        run: bundle exec rspec #Cambiar por unittest o agregarlo
      
      - name: Store coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/ #Completar
